[build]
  command = "npm run build"
  publish = "dist/stockpro-angular"

[[redirects]]
  from = "/api/*"
  to = "http://13.232.138.180:8080/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/oauth2/*"
  to = "http://13.232.138.180:8080/oauth2/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/login/oauth2/*"
  to = "http://13.232.138.180:8080/login/oauth2/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
