const fs = require("fs");
const path = require("path");

const rootDir = path.resolve(__dirname, "..");
const envPath = path.join(rootDir, ".env");
const outputPath = path.join(rootDir, "src", "app", "core", "generated-env.ts");

const defaults = {
  API_BASE_URL: "/api/v1",
  RAZORPAY_CHECKOUT_SCRIPT_URL: "https://checkout.razorpay.com/v1/checkout.js",
  RAZORPAY_MAX_AMOUNT_INR: "500000"
};

function parseEnv(content) {
  return content.split(/\r?\n/).reduce((values, line) => {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) return values;

    const separator = trimmed.indexOf("=");
    if (separator === -1) return values;

    const key = trimmed.slice(0, separator).trim();
    let value = trimmed.slice(separator + 1).trim();

    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }

    values[key] = value;
    return values;
  }, {});
}

const fileValues = fs.existsSync(envPath) ? parseEnv(fs.readFileSync(envPath, "utf8")) : {};
const runtimeValues = Object.fromEntries(
  Object.keys(defaults)
    .filter((key) => process.env[key])
    .map((key) => [key, process.env[key]])
);
const env = { ...defaults, ...fileValues, ...runtimeValues };

const output = `// This file is generated by scripts/generate-env.js. Do not edit by hand.
export const ENV = ${JSON.stringify(env, null, 2)} as const;
`;

fs.writeFileSync(outputPath, output);
console.log(`Generated ${path.relative(rootDir, outputPath)} from .env`);
